language: ruby
rvm:
- 2.1.1
branches: all
CODECLIMATE_REPO_TOKEN=d74c8d540dd2ea1dbb537265c3a87cbe0a12da35a43539932e4eab39388d2295
script: bundle exec rspec
addons:
  postgresql: "9.3"
  # sauce_connect:
  #   username: "sameertotey"
  #   access_key: "713b2903-3584-4621-a685-9de3aa060f6f"
before_script:
  - psql -c 'create database scheduling_app_test;' -U postgres

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - sleep 3 # give xvfb some time to start
  # - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc