# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
  facebook_key: "669919506378230"
  facebook_secret: "2686bab9534d9a1ff1364903ce074d03"

  twitter_key: "XR033ZxAOSlAjYf6NPxNeA"
  twitter_secret: "VkKj9WyYlJzWbZWUGqY0KmVhT1pBr69ltPcqFu8VKU"

  github_key: "d098818c9f27020adba5"
  github_secret: "4702fb398299a62c4bc43c29b959a86c6ee0940b"

  linkedin_key: "75wxisxv9io02o"
  linkedin_secret: "CQWB9D7XQlSU6BLf"

  google_key: "61759669911-n0n0n8mfkl9hhsa422etnul67gc7a1t4.apps.googleusercontent.com"
  google_secret: "I__qCHF-HdtqGAAX_ZsRrdTb"

production:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "YOUR_KEY"
  twitter_secret: "YOUR_SECRET"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
